"""
Automated test script for the Text File Merger application
Tests the core merging functionality without GUI
"""

import os
import sys
import json
from pathlib import Path
from datetime import datetime


class Config:
    """Handles persistent configuration storage"""

    def __init__(self, config_file: str = "config.json"):
        self.config_file = config_file
        self.data = self.load()

    def load(self):
        """Load configuration from file"""
        if os.path.exists(self.config_file):
            try:
                with open(self.config_file, 'r') as f:
                    return json.load(f)
            except Exception as e:
                print(f"Error loading config: {e}")
                return self.default_config()
        return self.default_config()

    def save(self):
        """Save configuration to file"""
        try:
            with open(self.config_file, 'w') as f:
                json.dump(self.data, f, indent=2)
        except Exception as e:
            print(f"Error saving config: {e}")

    @staticmethod
    def default_config():
        """Return default configuration"""
        return {
            "output_folder": "",
            "file_extensions": ".txt, .py, .md, .json, .xml, .csv"
        }

    def get(self, key: str, default=None):
        """Get configuration value"""
        return self.data.get(key, default)

    def set(self, key: str, value):
        """Set configuration value and save"""
        self.data[key] = value
        self.save()


def test_file_collection():
    """Test file collection with different settings"""
    print("Testing file collection...")

    # Create a mock app instance (without GUI)
    class MockApp:
        def __init__(self):
            self.config = Config()

        def get_file_extensions(self):
            return ['.txt', '.py', '.md', '.json', '.csv']

        def collect_files(self, folder_path, exclude_subfolders, extensions):
            files = []
            folder = Path(folder_path)

            if exclude_subfolders:
                for file_path in folder.iterdir():
                    if file_path.is_file() and file_path.suffix.lower() in extensions:
                        files.append(file_path)
            else:
                for ext in extensions:
                    files.extend(folder.rglob(f"*{ext}"))

            return sorted(files)

        def merge_files(self, files, output_path):
            try:
                with open(output_path, 'w', encoding='utf-8', errors='ignore') as outfile:
                    outfile.write(f"Generated by AI Context Assistant\n")
                    outfile.write(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                    outfile.write(f"Total files: {len(files)}\n")
                    outfile.write("\n" + "="*80 + "\n\n")

                    for file_path in files:
                        try:
                            outfile.write("="*80 + "\n")
                            outfile.write(f"BEGIN FILE: {file_path}\n")
                            outfile.write("="*80 + "\n")

                            with open(file_path, 'r', encoding='utf-8', errors='ignore') as infile:
                                content = infile.read()
                                outfile.write(content)
                                if content and not content.endswith('\n'):
                                    outfile.write('\n')

                            outfile.write("="*80 + "\n")
                            outfile.write(f"END FILE: {file_path}\n")
                            outfile.write("="*80 + "\n\n")

                        except Exception as e:
                            print(f"Error reading {file_path}: {e}")
                            continue

                return True
            except Exception as e:
                print(f"Error writing output file: {e}")
                return False

    app = MockApp()
    extensions = app.get_file_extensions()

    # Test 1: Collect files from project1 with subfolders
    print("\nTest 1: Collecting files from project1 (with subfolders)")
    files1 = app.collect_files("test_data/project1", False, extensions)
    print(f"  Found {len(files1)} files")
    for f in files1:
        print(f"    - {f}")
    assert len(files1) == 5, f"Expected 5 files, got {len(files1)}"

    # Test 2: Collect files from project1 without subfolders
    print("\nTest 2: Collecting files from project1 (exclude subfolders)")
    files2 = app.collect_files("test_data/project1", True, extensions)
    print(f"  Found {len(files2)} files")
    for f in files2:
        print(f"    - {f}")
    assert len(files2) == 3, f"Expected 3 files, got {len(files2)}"

    # Test 3: Collect files from project2 with subfolders
    print("\nTest 3: Collecting files from project2 (with subfolders)")
    files3 = app.collect_files("test_data/project2", False, extensions)
    print(f"  Found {len(files3)} files")
    for f in files3:
        print(f"    - {f}")
    assert len(files3) == 4, f"Expected 4 files, got {len(files3)}"

    # Test 4: Merge files
    print("\nTest 4: Merging files")
    output_path = "test_data/output/test_merge.txt"
    success = app.merge_files(files1, output_path)
    assert success, "Merge failed"
    assert os.path.exists(output_path), "Output file not created"

    # Check output file content
    with open(output_path, 'r') as f:
        content = f.read()
        assert "Generated by AI Context Assistant" in content
        assert "BEGIN FILE:" in content
        assert "END FILE:" in content
        print(f"  Output file created: {output_path}")
        print(f"  Output file size: {len(content)} characters")

    print("\n" + "="*60)
    print("All tests passed!")
    print("="*60)


def test_config():
    """Test configuration persistence"""
    print("\nTesting configuration...")

    # Create test config
    test_config_file = "test_config.json"
    if os.path.exists(test_config_file):
        os.remove(test_config_file)

    config = Config(test_config_file)

    # Test default values
    assert config.get("output_folder") == ""
    assert ".txt" in config.get("file_extensions")

    # Test setting values
    config.set("output_folder", "C:\\Test\\Output")
    config.set("file_extensions", ".py, .js")

    # Test persistence
    config2 = Config(test_config_file)
    assert config2.get("output_folder") == "C:\\Test\\Output"
    assert config2.get("file_extensions") == ".py, .js"

    # Cleanup
    os.remove(test_config_file)

    print("  Configuration tests passed!")


if __name__ == "__main__":
    try:
        print("="*60)
        print("Running Text File Merger Tests")
        print("="*60)

        # Check if test data exists
        if not os.path.exists("test_data/project1"):
            print("\nError: Test data not found!")
            print("Please run: python create_test_data.py")
            sys.exit(1)

        test_config()
        test_file_collection()

        print("\n" + "="*60)
        print("SUCCESS: All tests completed successfully!")
        print("="*60)

    except AssertionError as e:
        print(f"\n❌ Test failed: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
